name: Conventional Commits Check

on:
  push:
    branches:
      - main
      - backend

jobs:
  conventional-commits-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make script executable
        run: chmod +x ./check-commits

      - name: Check conventional commits
        run: ./check-commits
